name: NestJS Continuous Integration

# สั่งให้ทำงานเมื่อมีการ Push เข้า branch main
on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      # 1. ดึงโค้ดจาก GitHub มาที่เครื่องหุ่นยนต์
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. ติดตั้ง Node.js เพื่อรัน Test
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # 3. รัน Unit Test (ถ้า Test พัง ขั้นตอนต่อไปจะไม่ทำงาน)
      - name: Run Tests
        run: npm test

      # 4. ลอง Build Docker Image (เช็กว่า Dockerfile เราไม่มีปัญหา)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # แค่ลอง build เช็กดูก่อน ยังไม่ push ขึ้น Registry
          tags: my-app:latest

      # 5. Login เข้าสู่ Github Container Registry
      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6. Build และ Push ของจริงขึ้นคลังเก็บ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # เปลี่ยนจาก false เป็น true เพื่อส่งขึ้นคลัง
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/nestjs-api:latest
            ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/nestjs-api:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-app:latest" # ชื่อ image ที่เรา build เช็กในเครื่องหุ่นยนต์
          format: "table"
          exit-code: "1" # ถ้าเจอช่องโหว่ร้ายแรง (Critical) ให้ทำเครื่องหมายกากบาทสีแดง ❌ ทันที
          severity: "CRITICAL,HIGH"
